apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: run-java8-
spec:
  pipelineRef:
    name: build-and-deploy-java-8
  # https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#specifying-parameters
  # You can specify Parameters that you want to pass to the Pipeline during execution, including different values of the same parameter for different Tasks in the Pipeline.
  # Note: You must specify all the Parameters that the Pipeline expects. Parameters that have default values specified in Pipeline are not required to be provided by PipelineRun.
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: manifest-dir
    type: string
    description: The directory in source that contains yaml manifests - used in 01_apply_manifest_task.yaml
    default: "k8s"
  - name: IMAGE
    type: string
    description: image to be build from the code    
  workspaces:
  - name: maven-settings
    configMap:
      name: custom-maven-settings
      items:
      - key: settings.xml
        path: settings.xml
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 500Mi         